name = "portfolio-website"
compatibility_date = "2023-06-23"

[build]
command = "./build.sh"
[build.environment]
NODE_VERSION = "20.10.0"
NPM_FLAGS = "--legacy-peer-deps"

[build.upload]
format = "directory"
dir = "dist"